# -*- coding: utf-8 -*-
"""Copy of Assignment 05. Probability | Nexus | RezaShokrzad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nG5vSEGLjMIS0zQkiwvLdCvE5NKbY2Jh

# 📓 Assignment 5 — Probability


<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------


## 🎲 Counting & Probability with Cards in Python 🃏
Learn factorials, combinations, and (conditional) probability — all in one simple card game simulation using only math and random modules.

## 🧮 PART 1: Factorial & Combinations
"""

# ---- FACTORIAL & COMBINATIONS ----

import math
print("6! =", math.factorial(6))
print("Combinations (6 choose 3):", math.comb(6,3))

"""## 🃏 PART 2: Simulating a Deck of Cards


"""

# ---- PROBABILITY IN A DECK ----

import random

deck = [f"{rank} of {suit}" for suit in ['Hearts', 'Spades', 'Diamonds', 'Clubs']
        for rank in range(1, 14)]
print(deck)

# Draw 2 random cards

draws = random.sample(deck, 2)
print("\nDrawn cards:", draws)

"""## 📊 PART 3: Basic Probability"""

# PROBABILITY: What’s the chance that both cards are Hearts?

hearts = [card for card in deck if "Hearts" in card]
print(f"deck: {deck}")
print(f"hearts: {hearts}")

#len(hearts) = number of Hearts cards = 13
#len(deck) = total cards = 52
#number of ways to choose 2 cards from Hearts = C(13,2) = 78
#total number of ways to choose 2 cards from 52 cards = C(52,2) = 1326

prob_both_hearts = math.comb(len(hearts), 2) / math.comb(len(deck), 2)
print(f"Probability both cards are Hearts: {prob_both_hearts:.4f}")

"""## 🔁 PART 4: Conditional Probability"""

# ---- CONDITIONAL PROBABILITY ----
# P(A and B) / P(B): Probability second card is Heart given first was Heart
# A = both are hearts, B = first is heart
prob_a_heart = math.comb(len(hearts), 1) / math.comb(len(deck), 1)
print(f"Probability a card is Heart: {prob_a_heart:.4f}")
hearts.pop()
deck.pop()
p_a_and_b = math.comb(len(hearts), 1) / math.comb(len(deck), 1) # after one heart is drawn
p_b = 13 / 52

p_a_given_b = p_a_and_b / p_b
print(f"Conditional probability 2nd card is Heart given 1st is Heart: {p_a_given_b:.4f}")